spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
  kafka:
    topicName: myTopic
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
  data:
    mongodb:
      host: localhost
      port: 0